-- Migration: Create USERS table
-- Stores user demographic and profile information

CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

    -- User Identity
    user_name VARCHAR(255) NOT NULL,
    email_id VARCHAR(255) UNIQUE NOT NULL,

    -- Demographics (used by Customer Context Agent)
    age INTEGER,
    base_location VARCHAR(255), -- "City, State" format
    base_zip VARCHAR(20),
    gender VARCHAR(50), -- 'Male', 'Female'

    -- Vector embeddings for future personalization
    embeddings vector(1536), -- User profile embeddings for survey personalization (reserved for future use)

    -- Mock Data Tracking
    is_mock BOOLEAN DEFAULT false, -- true = generated by MOCK_USR_MINI_AGENT, false = from form
    is_main_user BOOLEAN DEFAULT false, -- true = from form submission (only one per simulation)

    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Constraints
    CONSTRAINT check_age CHECK (age > 0 AND age < 150)
);

-- Indexes for users
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email_id);
CREATE INDEX IF NOT EXISTS idx_users_base_zip ON users(base_zip);
CREATE INDEX IF NOT EXISTS idx_users_embeddings ON users USING ivfflat(embeddings vector_cosine_ops) WITH (lists = 100);
CREATE INDEX IF NOT EXISTS idx_users_is_main_user ON users(is_main_user) WHERE is_main_user = true;
CREATE INDEX IF NOT EXISTS idx_users_is_mock ON users(is_mock);

-- Comments
COMMENT ON TABLE users IS 'User profiles with demographics for personalized survey generation';
COMMENT ON COLUMN users.embeddings IS 'User profile embeddings for personalization (reserved for future survey framework enhancements)';
COMMENT ON COLUMN users.is_mock IS 'false = main user from form, true = generated user by MOCK_USR_MINI_AGENT';
COMMENT ON COLUMN users.is_main_user IS 'true = user from form submission (survey target), false = generated user';
