-- Migration: Create USERS table
-- Stores user demographic and profile information with engagement metrics

CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

    -- User Identity
    user_name VARCHAR(255) NOT NULL,
    email_id VARCHAR(255) UNIQUE NOT NULL,

    -- Demographics (used by Customer Context Agent)
    age INTEGER,
    base_location VARCHAR(255), -- "City, State" format
    base_zip VARCHAR(20),
    gender VARCHAR(50), -- 'Male', 'Female'

    -- Vector embeddings for future personalization
    embeddings vector(1536), -- User profile embeddings for survey personalization (reserved for future use)

    -- Engagement Metrics (calculated by MOCK_USR_MINI_AGENT, used by Customer Context Agent)
    total_purchases INTEGER DEFAULT 0,
    total_reviews INTEGER DEFAULT 0,
    review_engagement_rate DECIMAL(4,3) DEFAULT 0.000, -- % of purchases reviewed (0.000-1.000)
    avg_review_rating DECIMAL(3,2) DEFAULT 0.00, -- Average star rating (0.00-5.00)
    sentiment_tendency VARCHAR(20) DEFAULT 'neutral', -- positive, critical, balanced, polarized, neutral
    engagement_level VARCHAR(30) DEFAULT 'new_user', -- highly_engaged, moderately_engaged, passive_buyer, new_user

    -- Mock Data Tracking
    is_main_user BOOLEAN DEFAULT false, -- true = from form submission (only one per simulation), false = generated by MOCK_USR_MINI_AGENT

    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Constraints
    CONSTRAINT check_age CHECK (age > 0 AND age < 150),
    CONSTRAINT check_total_purchases CHECK (total_purchases >= 0),
    CONSTRAINT check_total_reviews CHECK (total_reviews >= 0 AND total_reviews <= total_purchases),
    CONSTRAINT check_review_engagement_rate CHECK (review_engagement_rate >= 0.000 AND review_engagement_rate <= 1.000),
    CONSTRAINT check_avg_review_rating CHECK (avg_review_rating >= 0.00 AND avg_review_rating <= 5.00),
    CONSTRAINT check_sentiment_tendency CHECK (sentiment_tendency IN ('positive', 'critical', 'balanced', 'polarized', 'neutral')),
    CONSTRAINT check_engagement_level CHECK (engagement_level IN ('highly_engaged', 'moderately_engaged', 'passive_buyer', 'new_user'))
);

-- Indexes for users
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email_id);
CREATE INDEX IF NOT EXISTS idx_users_base_zip ON users(base_zip);
CREATE INDEX IF NOT EXISTS idx_users_embeddings ON users USING ivfflat(embeddings vector_cosine_ops) WITH (lists = 100);
CREATE INDEX IF NOT EXISTS idx_users_is_main_user ON users(is_main_user) WHERE is_main_user = true;
CREATE INDEX IF NOT EXISTS idx_users_engagement_rate ON users(review_engagement_rate);
CREATE INDEX IF NOT EXISTS idx_users_engagement_level ON users(engagement_level);
CREATE INDEX IF NOT EXISTS idx_users_sentiment ON users(sentiment_tendency);

-- Comments
COMMENT ON TABLE users IS 'User profiles with demographics and engagement metrics for personalized survey generation';
COMMENT ON COLUMN users.embeddings IS 'User profile embeddings for personalization (reserved for future survey framework enhancements)';
COMMENT ON COLUMN users.is_main_user IS 'true = user from form submission (survey target), false = generated user by MOCK_USR_MINI_AGENT';
COMMENT ON COLUMN users.total_purchases IS 'Total number of transactions (calculated after data generation)';
COMMENT ON COLUMN users.total_reviews IS 'Total number of reviews written (calculated after data generation)';
COMMENT ON COLUMN users.review_engagement_rate IS 'Percentage of purchases that were reviewed: total_reviews / total_purchases';
COMMENT ON COLUMN users.avg_review_rating IS 'Average star rating across all user reviews';
COMMENT ON COLUMN users.sentiment_tendency IS 'Review sentiment pattern based on rating distribution';
COMMENT ON COLUMN users.engagement_level IS 'User engagement category based on review count and engagement rate';
