-- Migration: Create TRANSACTIONS table
-- Stores purchase and delivery information

CREATE TABLE IF NOT EXISTS transactions (
    transaction_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    item_id VARCHAR(20) NOT NULL REFERENCES products(item_id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,

    -- Transaction timeline
    order_date TIMESTAMP WITH TIME ZONE NOT NULL,
    delivery_date TIMESTAMP WITH TIME ZONE,
    expected_delivery_date TIMESTAMP WITH TIME ZONE, -- For analyzing late deliveries (future survey framework)
    return_date TIMESTAMP WITH TIME ZONE, -- For analyzing returns (future survey framework)

    -- Pricing
    original_price DECIMAL(12, 2) NOT NULL, -- From products.price
    retail_price DECIMAL(12, 2) NOT NULL, -- Actual price paid (with discounts)

    -- Status tracking
    transaction_status VARCHAR(50) DEFAULT 'delivered', -- 'pending', 'shipped', 'delivered', 'returned'

    -- Mock Data Tracking
    is_mock BOOLEAN DEFAULT false, -- true = generated by MOCK_TRX_MINI_AGENT

    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Constraints
    CONSTRAINT check_delivery_date CHECK (delivery_date IS NULL OR delivery_date >= order_date),
    CONSTRAINT check_expected_delivery CHECK (expected_delivery_date IS NULL OR expected_delivery_date >= order_date),
    CONSTRAINT check_return_date CHECK (return_date IS NULL OR return_date >= delivery_date),
    CONSTRAINT check_prices CHECK (original_price >= retail_price AND retail_price > 0)
);

-- Indexes for transactions
CREATE INDEX IF NOT EXISTS idx_transactions_item_id ON transactions(item_id);
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_order_date ON transactions(order_date);
CREATE INDEX IF NOT EXISTS idx_transactions_status ON transactions(transaction_status);
CREATE INDEX IF NOT EXISTS idx_transactions_is_mock ON transactions(is_mock);

-- Comments
COMMENT ON TABLE transactions IS 'Purchase and delivery tracking';
COMMENT ON COLUMN transactions.expected_delivery_date IS 'For analyzing late deliveries in survey framework';
COMMENT ON COLUMN transactions.return_date IS 'For analyzing product returns in survey framework';
COMMENT ON COLUMN transactions.is_mock IS 'true = generated by MOCK_TRX_MINI_AGENT, false = real transaction data';
