-- ============================================================================
-- Survey Sensei - Master Reset Script
-- ============================================================================
-- This script drops all existing tables and recreates them from scratch
-- WARNING: This will DELETE ALL DATA in the database!
-- ============================================================================

-- Drop tables in reverse dependency order (drop dependent tables first)
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS survey_sessions CASCADE;
DROP TABLE IF EXISTS survey CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS products CASCADE;

-- Drop functions
DROP FUNCTION IF EXISTS match_products(vector, int, int) CASCADE;
DROP FUNCTION IF EXISTS update_updated_at_column() CASCADE;

-- Note: Extensions are kept enabled (uuid-ossp, vector)
-- ============================================================================

-- Migration: Enable PostgreSQL Extensions
-- Required extensions for Survey Sensei

-- UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Vector embeddings (pgvector)
CREATE EXTENSION IF NOT EXISTS "vector";


-- Migration: Create PRODUCTS table
-- Stores product/item information from Amazon (via RapidAPI)
-- Schema aligned with RapidAPI "Real-Time Amazon Data" API response

CREATE TABLE IF NOT EXISTS products (
    -- Primary Key: ASIN (Amazon Standard Identification Number)
    item_id VARCHAR(20) PRIMARY KEY, -- 10-character ASIN from Amazon (e.g., 'B09YW8BZDP')

    -- Product Details (from RapidAPI product-details endpoint)
    product_url TEXT NOT NULL, -- Direct Amazon product page URL
    title TEXT NOT NULL, -- Product title/name
    brand VARCHAR(255), -- Manufacturer/brand name
    description TEXT, -- Product description
    photos JSONB, -- Array of product image URLs (from product_photos field)
    price DECIMAL(12, 2), -- Current product price
    star_rating DECIMAL(3, 2), -- Average star rating (e.g., 4.7)
    num_ratings INTEGER DEFAULT 0, -- Total number of ratings/reviews (from RapidAPI)
    review_count INTEGER DEFAULT 0, -- Actual review count in our database (auto-updated by trigger)
    category VARCHAR(50) DEFAULT 'general', -- Product category (electronics, clothing, home, etc.)

    -- Vector embeddings for semantic search
    embeddings vector(1536), -- OpenAI ada-002 dimension for product similarity

    -- Mock Data Tracking
    is_mock BOOLEAN DEFAULT false, -- true = generated by MOCK_PDT_MINI_AGENT, false = from RapidAPI

    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Constraints
    CONSTRAINT check_price CHECK (price >= 0),
    CONSTRAINT check_star_rating CHECK (star_rating >= 0 AND star_rating <= 5),
    CONSTRAINT check_num_ratings CHECK (num_ratings >= 0),
    CONSTRAINT check_review_count CHECK (review_count >= 0)
);

-- Indexes for products
CREATE INDEX IF NOT EXISTS idx_products_brand ON products(brand);
CREATE INDEX IF NOT EXISTS idx_products_star_rating ON products(star_rating);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_products_embeddings ON products USING ivfflat(embeddings vector_cosine_ops) WITH (lists = 100);
CREATE INDEX IF NOT EXISTS idx_products_is_mock ON products(is_mock);

-- Comments
COMMENT ON TABLE products IS 'Amazon product catalog fetched via RapidAPI Real-Time Amazon Data API';
COMMENT ON COLUMN products.item_id IS 'ASIN - Amazon Standard Identification Number (10 alphanumeric characters)';
COMMENT ON COLUMN products.product_url IS 'Direct link to Amazon product page (from product_url field)';
COMMENT ON COLUMN products.title IS 'Product title/name (from product_title field)';
COMMENT ON COLUMN products.brand IS 'Manufacturer/brand name (from brand field)';
COMMENT ON COLUMN products.description IS 'Product description (from product_description field)';
COMMENT ON COLUMN products.photos IS 'Array of image URLs (from product_photos field)';
COMMENT ON COLUMN products.price IS 'Current product price in USD (from product_price field)';
COMMENT ON COLUMN products.star_rating IS 'Average star rating 1-5 (from product_star_rating field)';
COMMENT ON COLUMN products.num_ratings IS 'Total number of ratings/reviews from RapidAPI (product_num_ratings field)';
COMMENT ON COLUMN products.review_count IS 'Actual count of reviews in our database (auto-updated by trigger_update_review_count)';
COMMENT ON COLUMN products.category IS 'Product category detected by MOCK_PDT_MINI_AGENT (electronics, clothing, home, etc.)';
COMMENT ON COLUMN products.embeddings IS 'Vector embeddings for semantic product similarity search';
COMMENT ON COLUMN products.is_mock IS 'false = main product from form/RapidAPI, true = generated similar product by MOCK_PDT_MINI_AGENT';


-- Migration: Create USERS table
-- Stores user demographic and profile information with engagement metrics

CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

    -- User Identity
    user_name VARCHAR(255) NOT NULL,
    email_id VARCHAR(255) UNIQUE NOT NULL,

    -- Demographics (used by Customer Context Agent)
    age INTEGER,
    base_location VARCHAR(255), -- "City, State" format
    base_zip VARCHAR(20),
    gender VARCHAR(50), -- 'Male', 'Female'

    -- Vector embeddings for future personalization
    embeddings vector(1536), -- User profile embeddings for survey personalization (reserved for future use)

    -- Engagement Metrics (calculated by MOCK_USR_MINI_AGENT, used by Customer Context Agent)
    total_purchases INTEGER DEFAULT 0,
    total_reviews INTEGER DEFAULT 0,
    review_engagement_rate DECIMAL(4,3) DEFAULT 0.000, -- % of purchases reviewed (0.000-1.000)
    avg_review_rating DECIMAL(3,2) DEFAULT 0.00, -- Average star rating (0.00-5.00)
    sentiment_tendency VARCHAR(20) DEFAULT 'neutral', -- positive, critical, balanced, polarized, neutral
    engagement_level VARCHAR(30) DEFAULT 'new_user', -- highly_engaged, moderately_engaged, passive_buyer, new_user

    -- Mock Data Tracking
    is_main_user BOOLEAN DEFAULT false, -- true = from form submission (only one per simulation), false = generated by MOCK_USR_MINI_AGENT

    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Constraints
    CONSTRAINT check_age CHECK (age > 0 AND age < 150),
    CONSTRAINT check_total_purchases CHECK (total_purchases >= 0),
    CONSTRAINT check_total_reviews CHECK (total_reviews >= 0 AND total_reviews <= total_purchases),
    CONSTRAINT check_review_engagement_rate CHECK (review_engagement_rate >= 0.000 AND review_engagement_rate <= 1.000),
    CONSTRAINT check_avg_review_rating CHECK (avg_review_rating >= 0.00 AND avg_review_rating <= 5.00),
    CONSTRAINT check_sentiment_tendency CHECK (sentiment_tendency IN ('positive', 'critical', 'balanced', 'polarized', 'neutral')),
    CONSTRAINT check_engagement_level CHECK (engagement_level IN ('highly_engaged', 'moderately_engaged', 'passive_buyer', 'new_user'))
);

-- Indexes for users
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email_id);
CREATE INDEX IF NOT EXISTS idx_users_base_zip ON users(base_zip);
CREATE INDEX IF NOT EXISTS idx_users_embeddings ON users USING ivfflat(embeddings vector_cosine_ops) WITH (lists = 100);
CREATE INDEX IF NOT EXISTS idx_users_is_main_user ON users(is_main_user) WHERE is_main_user = true;
CREATE INDEX IF NOT EXISTS idx_users_engagement_rate ON users(review_engagement_rate);
CREATE INDEX IF NOT EXISTS idx_users_engagement_level ON users(engagement_level);
CREATE INDEX IF NOT EXISTS idx_users_sentiment ON users(sentiment_tendency);

-- Comments
COMMENT ON TABLE users IS 'User profiles with demographics and engagement metrics for personalized survey generation';
COMMENT ON COLUMN users.embeddings IS 'User profile embeddings for personalization (reserved for future survey framework enhancements)';
COMMENT ON COLUMN users.is_main_user IS 'true = user from form submission (survey target), false = generated user by MOCK_USR_MINI_AGENT';
COMMENT ON COLUMN users.total_purchases IS 'Total number of transactions (calculated after data generation)';
COMMENT ON COLUMN users.total_reviews IS 'Total number of reviews written (calculated after data generation)';
COMMENT ON COLUMN users.review_engagement_rate IS 'Percentage of purchases that were reviewed: total_reviews / total_purchases';
COMMENT ON COLUMN users.avg_review_rating IS 'Average star rating across all user reviews';
COMMENT ON COLUMN users.sentiment_tendency IS 'Review sentiment pattern based on rating distribution';
COMMENT ON COLUMN users.engagement_level IS 'User engagement category based on review count and engagement rate';


-- Migration: Create TRANSACTIONS table
-- Stores purchase and delivery information

CREATE TABLE IF NOT EXISTS transactions (
    transaction_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    item_id VARCHAR(20) NOT NULL REFERENCES products(item_id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,

    -- Transaction timeline
    order_date TIMESTAMP WITH TIME ZONE NOT NULL,
    delivery_date TIMESTAMP WITH TIME ZONE,
    expected_delivery_date TIMESTAMP WITH TIME ZONE, -- For analyzing late deliveries (future survey framework)
    return_date TIMESTAMP WITH TIME ZONE, -- For analyzing returns (future survey framework)

    -- Pricing
    original_price DECIMAL(12, 2) NOT NULL, -- From products.price
    retail_price DECIMAL(12, 2) NOT NULL, -- Actual price paid (with discounts)

    -- Status tracking
    transaction_status VARCHAR(50) DEFAULT 'delivered', -- 'pending', 'shipped', 'delivered', 'returned'

    -- Mock Data Tracking
    is_mock BOOLEAN DEFAULT false, -- true = generated by MOCK_TRX_MINI_AGENT

    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Constraints
    CONSTRAINT check_delivery_date CHECK (delivery_date IS NULL OR delivery_date >= order_date),
    CONSTRAINT check_expected_delivery CHECK (expected_delivery_date IS NULL OR expected_delivery_date >= order_date),
    CONSTRAINT check_return_date CHECK (return_date IS NULL OR return_date >= delivery_date),
    CONSTRAINT check_prices CHECK (original_price >= retail_price AND retail_price > 0)
);

-- Indexes for transactions
CREATE INDEX IF NOT EXISTS idx_transactions_item_id ON transactions(item_id);
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_order_date ON transactions(order_date);
CREATE INDEX IF NOT EXISTS idx_transactions_status ON transactions(transaction_status);
CREATE INDEX IF NOT EXISTS idx_transactions_is_mock ON transactions(is_mock);

-- Comments
COMMENT ON TABLE transactions IS 'Purchase and delivery tracking';
COMMENT ON COLUMN transactions.expected_delivery_date IS 'For analyzing late deliveries in survey framework';
COMMENT ON COLUMN transactions.return_date IS 'For analyzing product returns in survey framework';
COMMENT ON COLUMN transactions.is_mock IS 'true = generated by MOCK_TRX_MINI_AGENT, false = real transaction data';


-- Migration: Create REVIEWS table
-- Stores user reviews with embeddings for sentiment analysis

CREATE TABLE IF NOT EXISTS reviews (
    review_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    item_id VARCHAR(20) NOT NULL REFERENCES products(item_id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    transaction_id UUID NOT NULL REFERENCES transactions(transaction_id) ON DELETE CASCADE,

    -- Review content
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    review_title VARCHAR(500),
    review_text TEXT NOT NULL,
    review_stars INTEGER NOT NULL, -- 1-5

    -- Source tracking
    source VARCHAR(20) NOT NULL DEFAULT 'agent_generated', -- 'rapidapi', 'agent_generated', 'user_submitted'
    manual_or_agent_generated VARCHAR(20) NOT NULL DEFAULT 'agent', -- 'manual' (human-written), 'agent' (AI-generated)

    -- GenAI features
    embeddings vector(1536), -- Review embeddings for semantic analysis (reserved for future survey framework)

    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Constraints
    CONSTRAINT check_review_stars CHECK (review_stars >= 1 AND review_stars <= 5),
    CONSTRAINT check_source CHECK (source IN ('rapidapi', 'agent_generated', 'user_submitted')),
    CONSTRAINT check_manual_or_agent CHECK (manual_or_agent_generated IN ('manual', 'agent')),
    CONSTRAINT unique_review_per_transaction UNIQUE(transaction_id)
);

-- Indexes for reviews
CREATE INDEX IF NOT EXISTS idx_reviews_item_id ON reviews(item_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_transaction_id ON reviews(transaction_id);
CREATE INDEX IF NOT EXISTS idx_reviews_stars ON reviews(review_stars);
CREATE INDEX IF NOT EXISTS idx_reviews_embeddings ON reviews USING ivfflat(embeddings vector_cosine_ops) WITH (lists = 100);
CREATE INDEX IF NOT EXISTS idx_reviews_source ON reviews(source);
CREATE INDEX IF NOT EXISTS idx_reviews_manual_or_agent ON reviews(manual_or_agent_generated);

-- Comments
COMMENT ON TABLE reviews IS 'User-generated reviews with AI-generated embeddings and sentiment';
COMMENT ON COLUMN reviews.embeddings IS 'Review text embeddings for semantic analysis (reserved for future survey framework enhancements)';
COMMENT ON COLUMN reviews.source IS 'Provenance: rapidapi (scraped from Amazon), agent_generated (by MOCK_RVW_MINI_AGENT), user_submitted (from future survey)';
COMMENT ON COLUMN reviews.manual_or_agent_generated IS 'Content authorship: manual (human-written text), agent (AI-generated text)';


-- Migration: Create SURVEY table
-- Core table for the agentic GenAI survey system

CREATE TABLE IF NOT EXISTS survey (
    scenario_id UUID DEFAULT uuid_generate_v4(),
    item_id VARCHAR(20) NOT NULL REFERENCES products(item_id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    transaction_id UUID NOT NULL REFERENCES transactions(transaction_id) ON DELETE CASCADE,
    survey_id UUID REFERENCES reviews(review_id) ON DELETE CASCADE,
    question_id UUID DEFAULT uuid_generate_v4(),

    -- Question details
    question_number INTEGER NOT NULL,
    question TEXT NOT NULL,
    options_object JSONB, -- Flexible JSON structure for different question types
    selected_option TEXT, -- User's selected answer/option

    -- GenAI validation
    correctly_anticipates_user_sentiment BOOLEAN,

    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Composite primary key
    PRIMARY KEY (scenario_id, question_id),

    -- Constraints
    CONSTRAINT check_question_number CHECK (question_number > 0)
);

-- Indexes for survey
CREATE INDEX IF NOT EXISTS idx_survey_item_id ON survey(item_id);
CREATE INDEX IF NOT EXISTS idx_survey_user_id ON survey(user_id);
CREATE INDEX IF NOT EXISTS idx_survey_transaction_id ON survey(transaction_id);
CREATE INDEX IF NOT EXISTS idx_survey_survey_id ON survey(survey_id);
CREATE INDEX IF NOT EXISTS idx_survey_scenario_id ON survey(scenario_id);

-- Comments
COMMENT ON TABLE survey IS 'Core agentic survey system - dynamically generated questions';
COMMENT ON COLUMN survey.correctly_anticipates_user_sentiment IS 'Ground truth for training/fine-tuning the agent';


-- Migration: Create SURVEY_SESSIONS table
-- Tracks entire survey sessions for analytics and agent improvement

CREATE TABLE IF NOT EXISTS survey_sessions (
    session_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    transaction_id UUID NOT NULL REFERENCES transactions(transaction_id) ON DELETE CASCADE,

    -- Session metadata
    started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    completed_at TIMESTAMP WITH TIME ZONE,
    is_completed BOOLEAN DEFAULT FALSE,
    total_questions INTEGER DEFAULT 0,
    answered_questions INTEGER DEFAULT 0,

    -- Agent performance metrics
    average_confidence_score DECIMAL(3, 2),
    sentiment_prediction_accuracy DECIMAL(3, 2),

    -- Session context (for agent to maintain state)
    session_context JSONB, -- Stores conversation history, user preferences, etc.

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_survey_sessions_user_id ON survey_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_survey_sessions_transaction_id ON survey_sessions(transaction_id);
CREATE INDEX IF NOT EXISTS idx_survey_sessions_completed ON survey_sessions(is_completed);

-- Comments
COMMENT ON TABLE survey_sessions IS 'Tracks survey sessions for analytics and agent learning';


-- Migration: Create Triggers
-- Auto-update timestamps and derived fields

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply trigger to all tables
DROP TRIGGER IF EXISTS update_products_updated_at ON products;
CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON products
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_users_updated_at ON users;
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_transactions_updated_at ON transactions;
CREATE TRIGGER update_transactions_updated_at BEFORE UPDATE ON transactions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_reviews_updated_at ON reviews;
CREATE TRIGGER update_reviews_updated_at BEFORE UPDATE ON reviews
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_survey_updated_at ON survey;
CREATE TRIGGER update_survey_updated_at BEFORE UPDATE ON survey
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_survey_sessions_updated_at ON survey_sessions;
CREATE TRIGGER update_survey_sessions_updated_at BEFORE UPDATE ON survey_sessions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Function to update review_count on products
CREATE OR REPLACE FUNCTION update_product_review_count()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE products
        SET review_count = review_count + 1
        WHERE item_id = NEW.item_id;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE products
        SET review_count = review_count - 1
        WHERE item_id = OLD.item_id;
    END IF
;
    RETURN NULL;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS trigger_update_review_count ON reviews;
CREATE TRIGGER trigger_update_review_count
AFTER INSERT OR DELETE ON reviews
FOR EACH ROW EXECUTE FUNCTION update_product_review_count();


-- Migration: Enable Row Level Security (RLS)
-- Basic policies - adjust based on your auth strategy

-- Enable RLS on all tables
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE survey ENABLE ROW LEVEL SECURITY;
ALTER TABLE survey_sessions ENABLE ROW LEVEL SECURITY;

-- Allow anonymous read access to products (public catalog)
DROP POLICY IF EXISTS "Allow public read access to products" ON products;
CREATE POLICY "Allow public read access to products"
ON products FOR SELECT
TO anon
USING (true);

-- Users can only view their own data
DROP POLICY IF EXISTS "Users can view their own profile" ON users;
CREATE POLICY "Users can view their own profile"
ON users FOR SELECT
TO authenticated
USING (auth.uid()::uuid = user_id);

-- Users can only view their own transactions
DROP POLICY IF EXISTS "Users can view their own transactions" ON transactions;
CREATE POLICY "Users can view their own transactions"
ON transactions FOR SELECT
TO authenticated
USING (user_id = auth.uid()::uuid);

-- Users can view and create their own reviews
DROP POLICY IF EXISTS "Users can view their own reviews" ON reviews;
CREATE POLICY "Users can view their own reviews"
ON reviews FOR SELECT
TO authenticated
USING (user_id = auth.uid()::uuid);

DROP POLICY IF EXISTS "Users can create their own reviews" ON reviews;
CREATE POLICY "Users can create their own reviews"
ON reviews FOR INSERT
TO authenticated
WITH CHECK (user_id = auth.uid()::uuid);

-- Users can view their own survey questions
DROP POLICY IF EXISTS "Users can view their own survey questions" ON survey;
CREATE POLICY "Users can view their own survey questions"
ON survey FOR SELECT
TO authenticated
USING (user_id = auth.uid()::uuid);

-- Users can view their own survey sessions
DROP POLICY IF EXISTS "Users can view their own survey sessions" ON survey_sessions;
CREATE POLICY "Users can view their own survey sessions"
ON survey_sessions FOR SELECT
TO authenticated
USING (user_id = auth.uid()::uuid);


-- Migration: Add conversation_history column to existing survey_sessions table
-- This handles the case where the table exists but is missing this column

DO $$
BEGIN
    -- Check if conversation_history column exists
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
        AND table_name = 'survey_sessions'
        AND column_name = 'conversation_history'
    ) THEN
        -- Add the column
        ALTER TABLE survey_sessions
        ADD COLUMN conversation_history JSONB DEFAULT '[]'::jsonb;

        RAISE NOTICE 'Added conversation_history column to survey_sessions table';
    ELSE
        RAISE NOTICE 'conversation_history column already exists in survey_sessions table';
    END IF;
END $$;

-- Add comment
COMMENT ON COLUMN survey_sessions.conversation_history IS 'Stores conversation messages between agent and user during survey';


-- Function for vector similarity search on products
-- Used by Agent 1 to find similar products

CREATE OR REPLACE FUNCTION match_products(
  query_embedding vector(1536),
  match_threshold float DEFAULT 0.7,
  match_count int DEFAULT 5
)
RETURNS TABLE (
  item_id varchar,
  product_url text,
  title text,
  brand varchar,
  category varchar,
  price numeric,
  description text,
  embeddings vector(1536),
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    p.item_id,
    p.product_url,
    p.title,
    p.brand,
    p.category,
    p.price,
    p.description,
    p.embeddings,
    1 - (p.embeddings <=> query_embedding) AS similarity
  FROM products p
  WHERE 1 - (p.embeddings <=> query_embedding) > match_threshold
  ORDER BY p.embeddings <=> query_embedding
  LIMIT match_count;
END;
$$;

-- Add comment
COMMENT ON FUNCTION match_products IS 'Find similar products using cosine similarity on embeddings';
